### PR TITLE
Added MIT License to for open source contributions

### PR DESCRIPTION
**Pull request by yufanw**

### CODE REVIEW

**Comment by yufanw** [comment]
Also added code for new sass styling, more responsive structure. I forgot to branch it off before pushing, next time will branch off to separate pull requests

**Comment by robinsongz** [comment]
> _No description provided._

**Comment by robinsongz** [comment]
@yufanw looks good! I'm going to merge this pull request. I also want to have the footer stickied like the navbar, what do you think? Also change the font to something like this: https://dankmemer.lol/, with 'getting started' and 'commands' looking more separate. great job tho! thank you :+1:

**Comment by yufanw** [comment]
@robinsongz thanks! I'll take a look at that. Sticky footers are generally not too useful, navbars are more useful for tall pages. Having 2 sticky components on the main page gives too little vertical space on smaller screens, we can still do it but just keep it in mind!

**Pull request merged**
